/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppHome {}
  interface AppLevels {}
  interface AppPuzzle {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface XwordClue {
    'autofocus': boolean;
    'column': number;
    'invalid': boolean;
    'isDown': boolean;
    'length': number;
    'row': number;
    'squareSize': number;
    'value': string;
  }
  interface XwordPuzzle {
    'height': number;
    'squares': CluePosition[];
    'width': number;
  }
  interface XwordSquare {
    'status': string;
    'value': string;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppLevelsElement extends Components.AppLevels, HTMLStencilElement {}
  var HTMLAppLevelsElement: {
    prototype: HTMLAppLevelsElement;
    new (): HTMLAppLevelsElement;
  };

  interface HTMLAppPuzzleElement extends Components.AppPuzzle, HTMLStencilElement {}
  var HTMLAppPuzzleElement: {
    prototype: HTMLAppPuzzleElement;
    new (): HTMLAppPuzzleElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLXwordClueElement extends Components.XwordClue, HTMLStencilElement {}
  var HTMLXwordClueElement: {
    prototype: HTMLXwordClueElement;
    new (): HTMLXwordClueElement;
  };

  interface HTMLXwordPuzzleElement extends Components.XwordPuzzle, HTMLStencilElement {}
  var HTMLXwordPuzzleElement: {
    prototype: HTMLXwordPuzzleElement;
    new (): HTMLXwordPuzzleElement;
  };

  interface HTMLXwordSquareElement extends Components.XwordSquare, HTMLStencilElement {}
  var HTMLXwordSquareElement: {
    prototype: HTMLXwordSquareElement;
    new (): HTMLXwordSquareElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-levels': HTMLAppLevelsElement;
    'app-puzzle': HTMLAppPuzzleElement;
    'app-root': HTMLAppRootElement;
    'xword-clue': HTMLXwordClueElement;
    'xword-puzzle': HTMLXwordPuzzleElement;
    'xword-square': HTMLXwordSquareElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppLevels {}
  interface AppPuzzle {
    'match'?: MatchResults;
  }
  interface AppRoot {}
  interface XwordClue {
    'autofocus'?: boolean;
    'column'?: number;
    'invalid'?: boolean;
    'isDown'?: boolean;
    'length'?: number;
    'onSquareUpdate'?: (event: CustomEvent<any>) => void;
    'row'?: number;
    'squareSize'?: number;
    'value'?: string;
  }
  interface XwordPuzzle {
    'height'?: number;
    'squares'?: CluePosition[];
    'width'?: number;
  }
  interface XwordSquare {
    'status'?: string;
    'value'?: string;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-levels': AppLevels;
    'app-puzzle': AppPuzzle;
    'app-root': AppRoot;
    'xword-clue': XwordClue;
    'xword-puzzle': XwordPuzzle;
    'xword-square': XwordSquare;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-levels': LocalJSX.AppLevels & JSXBase.HTMLAttributes<HTMLAppLevelsElement>;
      'app-puzzle': LocalJSX.AppPuzzle & JSXBase.HTMLAttributes<HTMLAppPuzzleElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'xword-clue': LocalJSX.XwordClue & JSXBase.HTMLAttributes<HTMLXwordClueElement>;
      'xword-puzzle': LocalJSX.XwordPuzzle & JSXBase.HTMLAttributes<HTMLXwordPuzzleElement>;
      'xword-square': LocalJSX.XwordSquare & JSXBase.HTMLAttributes<HTMLXwordSquareElement>;
    }
  }
}


